# Generated by Django 4.1.7 on 2023-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default=1, max_length=255, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='item.item', verbose_name='Элементы'),
        ),
    ]
