# Generated by Django 4.1.7 on 2023-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_currency_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('GBP', 'Gbp')], max_length=255, verbose_name='Валюта'),
        ),
    ]
