version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=degea4057
      - POSTGRES_DB=rishad_back
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/home/RishadTEst/staticfiles/
      - media_volume:/home/RishadTEst/media/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/RishadTEst/staticfiles/
      - media_volume:/home/RishadTEst/media/
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: